### 卷积神经网络
#### 稀疏连接
#### 平移不变性
#### pytorch对卷积的封装

In [4]:
import torch
import torch.nn as nn

```python
#pytorch中的 Conv2d类,定义2d卷积类
class torch.nn.Conv2d(in_channels, 
                      out_channels, 
                      kernel_size, 
                      stride=1, 
                      padding=0, 
                      dilation=1, 
                      groups=1, 
                      bias=True, 
                      padding_mode='zeros', 
                      device=None, 
                      dtype=None)
```                      

In [9]:

input_feat = torch.tensor([[4, 1, 7, 5], [4, 4, 2, 5], [7, 7, 2, 4], [1, 0, 2, 4]], dtype=torch.float32).unsqueeze(0).unsqueeze(0)
print(input_feat)
print(input_feat.shape)
# 输出：

tensor([[[[4., 1., 7., 5.],
          [4., 4., 2., 5.],
          [7., 7., 2., 4.],
          [1., 0., 2., 4.]]]])
torch.Size([1, 1, 4, 4])


In [10]:
# 进行卷积操作
conv2d = nn.Conv2d(1, 1, (2, 2), stride=1, padding='same', bias=True)
# 默认情况随机初始化参数
print(conv2d.weight)
print(conv2d.bias)
# 输出：


Parameter containing:
tensor([[[[ 0.4655, -0.3793],
          [ 0.2556, -0.4438]]]], requires_grad=True)
Parameter containing:
tensor([-0.3370], requires_grad=True)


In [11]:
# 手动指定卷积核
conv2d = nn.Conv2d(1, 1, (2, 2), stride=1, padding='same', bias=False)
# 卷积核要有四个维度(输入通道数，输出通道数，高，宽)

kernels = torch.tensor([[[[1, 0], [2, 1]]]], dtype=torch.float32)
conv2d.weight = nn.Parameter(kernels, requires_grad=False)
print(conv2d.weight)
print(conv2d.bias)
# 输出：


Parameter containing:
tensor([[[[1., 0.],
          [2., 1.]]]])
None


In [14]:
output = conv2d(input_feat)
print(output)

tensor([[[[16., 11., 16., 15.],
          [25., 20., 10., 13.],
          [ 9.,  9., 10., 12.],
          [ 1.,  0.,  2.,  4.]]]])


#### 卷积的几种分类
* 深度可分离卷积  计算量更少
* 空洞卷积
* 转置卷积
* 残差卷积块
* Inception模块
* SE块