### 张量tensor的概念
Tensor 是深度学习框架中极为基础的概念，也是 PyTroch、TensorFlow 中最重要的知识点之一，它是一种数据的存储和处理结构。
#### 几个概念
* 标量，也称 Scalar，是一个只有大小，没有方向的量，比如 1.8、e、10 等
* 向量，也称 Vector，是一个有大小也有方向的量，比如 (1,2,3,4) 等。
* 矩阵，也称 Matrix，是多个向量合并在一起得到的量，比如[(1,2,3),(4,5,6)]等。
* 张量 (Tensor) 可以统一标量、向量、矩阵的概念
* Tensor 的概念中，使用 Rank（秩）来表示这种“维度”，标量，就是 Rank 为 0 阶的 Tensor；向量就是 Rank 为 1 阶的 Tensor；矩阵就是 Rank 为 2 阶的 Tensor

In [1]:
import torch
import numpy as np

#### 创建张量基本用法
`torch.tensor(data, dtype=None, device=None,requires_grad=False)`
* data，要传入模型的数据
* dtype，它声明了你需要返回一个怎样类型的 Tensor，具体类型可以参考前面表格里列举的 Tensor 的 8 种类型。
* requires_grad，用于说明当前量是否需要在计算中保留对应的梯度信息。
* device，这个参数指定了数据要返回到的设备
* requires_grad，用于说明当前量是否需要在计算中保留对应的梯度信息。只有当一个 Tensor 设置 requires_grad 为 True 的情况下，才会对这个 Tensor 以及由这个 Tensor 计算出来的其他 Tensor 进行求导，然后将导数值存在 Tensor 的 grad 属性中，便于优化器来更新参数。
* 把 requires_grad 设置成 true 或者 false 要灵活处理。如果是训练过程就要设置为 true，目的是方便求导、更新参数。而到了验证或者测试过程，我们的目的是检查当前模型的泛化能力，那就要把 requires_grad 设置成 Fasle，避免这个参数根据 loss 自动更新。

In [10]:
# 使用 torch
x = torch.tensor([1.0, 2.0, 3.0])
print(x)
a = torch.rand(2,4)
print(a)
b = torch.randperm(10)
print(b)
print(b.type())

tensor([1., 2., 3.])
tensor([[0.4032, 0.7474, 0.3448, 0.4291],
        [0.3893, 0.3258, 0.1644, 0.2924]])
tensor([4, 2, 7, 9, 3, 5, 0, 6, 1, 8])
torch.LongTensor


In [8]:
# 从numpy中转换数据
ndarry = np.array([1,2,3])
tensor_array = torch.from_numpy(ndarry)
print(tensor_array)

tensor([1, 2, 3], dtype=torch.int32)


#### 几种常见创建张量的用法
* 创建零矩阵 Tensor `torch.zeros(*size, dtype=None...)`
* 创建单位矩阵 Tensor：单位矩阵是指主对角线上的元素都为 1 的矩阵 `torch.eye(size, dtype=None...)`
* 创建全一矩阵 Tensor：全一矩阵顾名思义，就是所有的元素都为 1 的矩阵 `torch.ones(size, dtype=None...)`
* `torch.rand` 用于生成数据类型为浮点型且维度指定的随机 Tensor，随机生成的浮点数据在 0~1 区间均匀分布。
* `torch.randn` 用于生成数据类型为浮点型且维度指定的随机 Tensor，随机生成的浮点数的取值满足均值为 0、方差为 1 的标准正态分布。
* `torch.normal` 用于生成数据类型为浮点型且维度指定的随机 Tensor，可以指定均值和标准差。
* `torch.randint` 用于生成随机整数的 Tensor，其内部填充的是在[low,high) 均匀生成的随机整数。

In [ ]:
# 常见创建张量用法
torch.rand(size)
torch.randn(size)
torch.normal(mean, std, size)
torch.randint(low, high, size）

#### 张量、标量、向量、矩阵的转换


In [ ]:
#标量转换
a = torch.tensor(1)
b = a.item()
print(b)

1


In [12]:
# 向量转换
a = [1, 2, 3]
b = torch.tensor(a)
c = b.numpy().tolist()
print(a, b, c)


[1, 2, 3] tensor([1, 2, 3]) [1, 2, 3]


In [6]:
# 从numpy中转换数据
ndarry = np.array([1,2,3])
na = torch.tensor(ndarry)
print(na)

tensor([1, 2, 3])


In [8]:
# cpu与gpu切换
na.cuda()
# na.cpu()

tensor([1, 2, 3], device='cuda:0')

In [7]:
# 创建一个三维0向量
a=torch.zeros(2, 3, 5)
# 张量的维度信息，属性获取
print(a.shape)
# 张量的维度信息，方法获取
print(a.size())
# 张量元素个数
count = a.numel()
print(count)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])
30


In [10]:
# 矩阵转秩 维度转换
x = torch.randn(2,3,5)
print(x.shape)
#矩阵按照原始矩阵的2,1,0三个通道顺序进行转秩,可以一次性对多个维度进行转化
x = x.permute(2,1,0)
print(x.shape)
# 将矩阵
x = x.transpose(2,0)

torch.Size([2, 3, 5])
torch.Size([5, 3, 2])


In [15]:
# 形状改变
x = torch.randn(4, 4)
print(x.shape)
print(x)
# 通过view函数进行形变
x = x.view(2,8)
print(x.shape)
print(x)
# 进行维度变换
x = x.permute(1,0)
print(x.shape)
print(x)
# view无法处理内存不连续的数据
#x = x.view(4,4)
x = x.reshape(4,4)
print(x.shape)
print(x)

torch.Size([4, 4])
tensor([[-0.8668, -1.4835,  0.8716, -0.3166],
        [-1.2438, -0.5077, -0.7945, -0.9906],
        [-1.0614, -2.3561,  0.0124,  0.6183],
        [-1.4219, -2.8857, -1.8384,  0.1188]])
torch.Size([2, 8])
tensor([[-0.8668, -1.4835,  0.8716, -0.3166, -1.2438, -0.5077, -0.7945, -0.9906],
        [-1.0614, -2.3561,  0.0124,  0.6183, -1.4219, -2.8857, -1.8384,  0.1188]])
torch.Size([8, 2])
tensor([[-0.8668, -1.0614],
        [-1.4835, -2.3561],
        [ 0.8716,  0.0124],
        [-0.3166,  0.6183],
        [-1.2438, -1.4219],
        [-0.5077, -2.8857],
        [-0.7945, -1.8384],
        [-0.9906,  0.1188]])
torch.Size([4, 4])
tensor([[-0.8668, -1.0614, -1.4835, -2.3561],
        [ 0.8716,  0.0124, -0.3166,  0.6183],
        [-1.2438, -1.4219, -0.5077, -2.8857],
        [-0.7945, -1.8384, -0.9906,  0.1188]])


#### squeeze and unsqueeze
* squeeze 压缩维度,如果指定压缩维度为1，则允许压缩
* unsqueeze 扩大维度

In [ ]:
# 对张量进行维度增减
x = torch.rand(2,1, 3)
print(x.shape)
print(x)
# 将维度为1的维度删除,1的维度大小为1，所以可以删除
x = x.squeeze(1)
print(x.shape)
print(x)
# 维度大小不为1，为3，不允许删除
x = x.squeeze(1)
print(x.shape)
print(x)


torch.Size([2, 1, 3])
tensor([[[0.7666, 0.9499, 0.8547]],

        [[0.4880, 0.0754, 0.4169]]])
torch.Size([2, 3])
tensor([[0.7666, 0.9499, 0.8547],
        [0.4880, 0.0754, 0.4169]])
torch.Size([2, 3])
tensor([[0.7666, 0.9499, 0.8547],
        [0.4880, 0.0754, 0.4169]])


In [26]:
x = torch.rand(2,1,3)
print(x.shape)
print(x)
# 在第二维度插入一个维度
y = x.unsqueeze(2)
print(y.shape)
print(y)

torch.Size([2, 1, 3])
tensor([[[0.5976, 0.7018, 0.9851]],

        [[0.8096, 0.2992, 0.5045]]])
torch.Size([2, 1, 1, 3])
tensor([[[[0.5976, 0.7018, 0.9851]]],


        [[[0.8096, 0.2992, 0.5045]]]])


#### tensor的连接操作
* cat : 连接两个tensor

In [ ]:
A = torch.ones(3,3)
B = torch.ones(3,3) * 2
print(A)
print(B)
# 二维场景中按行进行拼接
C = torch.cat((A,B), dim=0)
print(C)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [28]:
# 二维场景中按列进行拼接
D=torch.cat((A,B),1)
print(D)

tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


#### tensor中的维度扩展连接操作，将2个tensor按维度连接扩展维度
* stack函数

In [30]:
# 创建一个标量，从0到4
A=torch.arange(0,4)
print(A)
B=torch.arange(5,9)
print(B)
# 进行维度拓展
C = torch.stack((A,B),0)
print(C.shape)
print(C)
D = torch.stack((A,B),1)
print(D.shape)
print(D)

tensor([0, 1, 2, 3])
tensor([5, 6, 7, 8])
torch.Size([2, 4])
tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])
torch.Size([4, 2])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])


In [36]:
## 二维转三维
A = torch.zeros(3,3)
B = torch.ones(3,3) * 2
C = torch.stack((A,B),dim=1)
print(C)
print(C.shape)

tensor([[[0., 0., 0.],
         [2., 2., 2.]],

        [[0., 0., 0.],
         [2., 2., 2.]],

        [[0., 0., 0.],
         [2., 2., 2.]]])
torch.Size([3, 2, 3])


#### tensor切分操作
* chunk 的作用就是将 Tensor 按照声明的 dim，进行尽可能平均的划分。
`torch.chunk(input, chunks, dim=0)`
input ：操作得目标张量
chunks ：切分份数，当无法均匀切分时，chunk 函数是先做除法，然后再向上取整得到每组的数量。
dim ：按那个维度进行切分

In [38]:
A=torch.tensor([1,2,3,4,5,6,7,8,9,10])
B = torch.chunk(A,3,0)
print(B)

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]), tensor([ 9, 10]))


In [ ]:
# 只能进行整数切分，切分成三个大小为1的向量
A=torch.tensor([1,2,3])
print(A)
B = torch.chunk(A,5,0)
print(B)

tensor([1, 2, 3])
(tensor([1]), tensor([2]), tensor([3]))


In [42]:
A=torch.ones(4,4)
print(A)
## 二维切分,按行切分
B= torch.chunk(A,2,dim=0)
print(B)
C = torch.chunk(A,2,dim=1)
print(C)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
(tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]), tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]))
(tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]))


In [43]:
A  = torch.ones(4,4,4)
print(A)
# 三维切分，按0轴切分，得到两个tensor
B = torch.chunk(A,2,dim=0)
print(B)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
(tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]), tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))


#### split 每份按照确定的大小来进行切分
`torch.split(tensor, split_size_or_sections, dim=0)`
* split_size_or_sections : 按每组split_size_or_sections来进行切分


In [ ]:
A=torch.rand(4,4)
print(A)
# 按每组3份来切分
B=torch.split(A, 3, 0)
print(B)

tensor([[0.6285, 0.3949, 0.1863, 0.6175],
        [0.3153, 0.2345, 0.4112, 0.3810],
        [0.6760, 0.8108, 0.0604, 0.1892],
        [0.4647, 0.3733, 0.4734, 0.0106]])
(tensor([[0.6285, 0.3949, 0.1863, 0.6175],
        [0.3153, 0.2345, 0.4112, 0.3810],
        [0.6760, 0.8108, 0.0604, 0.1892]]), tensor([[0.4647, 0.3733, 0.4734, 0.0106]]))


In [48]:
A=torch.rand(5,6)
print(A)
# 按2行，3行的规格沿着0轴进行切分
B= torch.split(A,(2,3),0)
print(B)

tensor([[0.0648, 0.1987, 0.0448, 0.0696, 0.1688, 0.9365],
        [0.0477, 0.0377, 0.9269, 0.3760, 0.1937, 0.2363],
        [0.1054, 0.7226, 0.1067, 0.3941, 0.1434, 0.8138],
        [0.4498, 0.4290, 0.0954, 0.3464, 0.8172, 0.9115],
        [0.8246, 0.9588, 0.6681, 0.6360, 0.0501, 0.1199]])
(tensor([[0.0648, 0.1987, 0.0448, 0.0696, 0.1688, 0.9365],
        [0.0477, 0.0377, 0.9269, 0.3760, 0.1937, 0.2363]]), tensor([[0.1054, 0.7226, 0.1067, 0.3941, 0.1434, 0.8138],
        [0.4498, 0.4290, 0.0954, 0.3464, 0.8172, 0.9115],
        [0.8246, 0.9588, 0.6681, 0.6360, 0.0501, 0.1199]]))


#### 降维切分 unbind,将一个维度删除
torch.unbind(input, dim=0)
将某一个维度进行切片

In [50]:
A=torch.arange(0,16).view(4,4)
print(A)
# 按0轴进行降维切分
B = torch.unbind(A,dim=0)
print(B)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]), tensor([12, 13, 14, 15]))


### tensor索引操作 对张量的一部分进行操作
* index_select(input, dim, index) 基于给定的索引来进行数据提取， index是torch.Tensor类型
* torch.masked_select(input, mask, out=None) 通过一些判断条件来进行选择 ，mask掩码张量,input 中“满足 mask 里面元素值为 True 的”对应位置的数据





In [ ]:
A=torch.arange(0,16).view(4,4)
print(A)
# 从第 0 维选择第 1（行）和 3（行）的数据
B= torch.index_select(A,0,torch.tensor([1,3]))
print(B)
# 从第 1 维选择第 0（列）和 3（列）的数据
C = torch.index_select(A,1,torch.tensor([0,3]))
print(C)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])
tensor([[ 0,  3],
        [ 4,  7],
        [ 8, 11],
        [12, 15]])


In [58]:
# masked_select 举例
A=torch.rand(5)
print(A)
mask = A > 0.3
print(mask)
# 从A中取出mask位置为true的元素
C = torch.masked_select(A, mask)
print(C)
#简化写法
C = torch.masked_select(A, A>0.3)
print(C)


tensor([0.3858, 0.7913, 0.1739, 0.9991, 0.3034])
tensor([ True,  True, False,  True,  True])
tensor([0.3858, 0.7913, 0.9991, 0.3034])
tensor([0.3858, 0.7913, 0.9991, 0.3034])


![image.png](image.png)

In [71]:
# 实际举例：提取出其中第一行的第一个，第二行的第一、第二个，第三行的最后一个
A=torch.tensor([[4,5,7], [3,9,8],[2,3,4]])
print(A)
B=torch.tensor([[1,0,0],[1,1,0],[0,0,1]])
print(B)
# A * B 每个元素对应位置相乘
print(A * B)
C=torch.masked_select(A, A*B!=0)
print(C)

mask = torch.tensor([[1, 0, 0], [1, 1, 0], [0, 0, 1]])
D = torch.masked_select(A, mask>0)
print(D)

eye  = torch.eye(3)
print(eye)
torch.masked_select(A,eye>0)



tensor([[4, 5, 7],
        [3, 9, 8],
        [2, 3, 4]])
tensor([[1, 0, 0],
        [1, 1, 0],
        [0, 0, 1]])
tensor([[4, 0, 0],
        [3, 9, 0],
        [0, 0, 4]])
tensor([4, 3, 9, 4])
tensor([4, 3, 9, 4])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


tensor([4, 9, 4])

定义一个需要求导的矩阵


In [3]:
x = torch.randn(3,4,requires_grad=True)
print(x)

tensor([[ 0.3435,  0.1521,  1.6209, -1.3845],
        [ 0.7553,  0.4105, -0.9160,  0.2289],
        [ 0.6783,  0.5005, -1.4680,  2.5069]], requires_grad=True)
