##tensor的属性

In [ ]:
torch.dtype # 类型，float,int 等
torch.device # 设备，cpu,cuda 等
torch.layouot # 布局，torch的内存布局对象，张量的非0元素坐标
torch.sparse_coo_tensor # 稀疏张量

In [3]:
import torch

In [6]:
indices = torch.tensor([[0,1,1],[2,0,2]])
values = torch.tensor([3,4,5],dtype=torch.float32)
x = torch.sparse_coo_tensor(indices,values,(3,3))
print(x)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)


In [12]:
# 定义device和dtype
# dev = torch.device("cpu")
dev = torch.device("cuda:0")
a = torch.tensor([2,2],dtype = torch.float32,device=dev)
print(a)

tensor([2., 2.], device='cuda:0')


In [17]:
# 稀疏张量
i=  torch.tensor([[0,1,1],[2,0,2]]) # 指定了张量值的坐标
v = torch.tensor([1,2,3])
res = torch.sparse_coo_tensor(i,v,(4,4),dtype=torch.float,device=dev)
dres = res.to_dense()
print(res)
print(dres)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([1., 2., 3.]),
       device='cuda:0', size=(4, 4), nnz=3, layout=torch.sparse_coo)
tensor([[0., 0., 1., 0.],
        [2., 0., 3., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')


### 算数运算
加减乘除
### 矩阵运算
高维tensor 的矩阵运算时需要保证最后两个维度之前的维度值是一致的,且最后两个维度可以进行矩阵运算
### 幂运算
### 开方运算
### 对数运算

In [20]:
# 加法
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)
print(a+b)
print(torch.add(a,b))
print(a.add(b))
# 结果赋值到a
print(a.add_(b))
print(a)

tensor([[0.9196, 0.9450, 0.4841],
        [0.8695, 0.8206, 0.0479]])
tensor([[0.4194, 0.8563, 0.2958],
        [0.6236, 0.5974, 0.9221]])
tensor([[1.3390, 1.8013, 0.7799],
        [1.4931, 1.4181, 0.9700]])
tensor([[1.3390, 1.8013, 0.7799],
        [1.4931, 1.4181, 0.9700]])
tensor([[1.3390, 1.8013, 0.7799],
        [1.4931, 1.4181, 0.9700]])
tensor([[1.3390, 1.8013, 0.7799],
        [1.4931, 1.4181, 0.9700]])
tensor([[1.3390, 1.8013, 0.7799],
        [1.4931, 1.4181, 0.9700]])


In [21]:
# 减法
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)
print(a-b)
print(torch.sub(a,b))
print(a.sub(b))
# 结果赋值到a
print(a.sub_(b))
print(a)

tensor([[0.7922, 0.3929, 0.5517],
        [0.7591, 0.3028, 0.8409]])
tensor([[0.8973, 0.1503, 0.8991],
        [0.7140, 0.4330, 0.8720]])
tensor([[-0.1051,  0.2426, -0.3474],
        [ 0.0451, -0.1302, -0.0311]])
tensor([[-0.1051,  0.2426, -0.3474],
        [ 0.0451, -0.1302, -0.0311]])
tensor([[-0.1051,  0.2426, -0.3474],
        [ 0.0451, -0.1302, -0.0311]])
tensor([[-0.1051,  0.2426, -0.3474],
        [ 0.0451, -0.1302, -0.0311]])
tensor([[-0.1051,  0.2426, -0.3474],
        [ 0.0451, -0.1302, -0.0311]])


In [23]:
# 乘法
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a*b)
print(a.mul(b))
print(torch.mul(a,b))
print(a.mul_(b))
print(a)

tensor([[0.0952, 0.0016, 0.2347],
        [0.0402, 0.3181, 0.1068]])
tensor([[0.0952, 0.0016, 0.2347],
        [0.0402, 0.3181, 0.1068]])
tensor([[0.0952, 0.0016, 0.2347],
        [0.0402, 0.3181, 0.1068]])
tensor([[0.0952, 0.0016, 0.2347],
        [0.0402, 0.3181, 0.1068]])
tensor([[0.0952, 0.0016, 0.2347],
        [0.0402, 0.3181, 0.1068]])


In [24]:
# 除法
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a/b)
print(torch.div(a,b))
print(a.div(b))
print(a.div_(b))
print(a)

tensor([[0.5581, 1.6319, 0.7655],
        [0.1109, 0.3351, 1.5593]])
tensor([[0.5581, 1.6319, 0.7655],
        [0.1109, 0.3351, 1.5593]])
tensor([[0.5581, 1.6319, 0.7655],
        [0.1109, 0.3351, 1.5593]])
tensor([[0.5581, 1.6319, 0.7655],
        [0.1109, 0.3351, 1.5593]])
tensor([[0.5581, 1.6319, 0.7655],
        [0.1109, 0.3351, 1.5593]])


In [26]:
# 矩阵运算
a= torch.ones(2,1)
b= torch.ones(1,2)
print(a)
print(b)
print(a @ b)
print(a.matmul(b))
print(a.mm(b))
print(torch.matmul(a,b))
print(torch.mm(a,b))

tensor([[1.],
        [1.]])
tensor([[1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [27]:
# 高维tensor运算

a = torch.ones(1,2,3,4)
b = torch.ones(1,2,4,3)
print(a)
print(b)
print(a.shape)
print(b.shape)
print(torch.matmul(a,b))
print(torch.matmul(a,b).shape)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
torch.Size([1, 2, 3, 4])
torch.Size([1, 2, 4, 3])
tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]],

         [[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]])
torch.Size([1, 2, 3, 3])


In [28]:
# 指数运算
a = torch.tensor([1,2])
print(a)
print(a.pow(3))
print(torch.pow(a,3))
print(a**3)
print(a.pow_(3))
print(a)

tensor([1, 2])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])


In [32]:
# 自然常数e的运算
a = torch.tensor([1,2],dtype=torch.float)
print(a.type())
print(torch.exp(a))
print(torch.exp_(a))
print(a)

torch.FloatTensor
tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])


In [36]:
# log 运算
a = torch.tensor([1, 2],dtype=torch.float)
print(torch.log(a))
print(torch.log2(a))
print(torch.log10(a))
print(torch.log_(a))
print(a)

tensor([0.0000, 0.6931])
tensor([0., 1.])
tensor([0.0000, 0.3010])
tensor([0.0000, 0.6931])
tensor([0.0000, 0.6931])


In [38]:
# 开平方
print(torch.sqrt(a))
print(a.sqrt())
print(torch.sqrt_(a))
print(a)

tensor([0.0000, 0.8326])
tensor([0.0000, 0.8326])
tensor([0.0000, 0.8326])
tensor([0.0000, 0.8326])


### inplace操作
原地操作，例如 x = x + y, x.add_(y)

### 广播机制
张量参数可以自动扩展为相同大小
广播机制需要满足的条件：
1. 张量至少有一个维度
2. 满足右对齐,最后一个维度大小相等

In [6]:
import torch

a = torch.rand(2,1,1,3)
b = torch.rand(2,3)
c = a +b
print(a)
print(b)
print(c)


tensor([[[[0.4804, 0.7826, 0.5970]]],


        [[[0.5676, 0.5489, 0.8073]]]])
tensor([[0.6312, 0.4364, 0.1802],
        [0.9089, 0.8854, 0.3300]])
tensor([[[[1.1116, 1.2191, 0.7771],
          [1.3893, 1.6680, 0.9270]]],


        [[[1.1988, 0.9854, 0.9875],
          [1.4765, 1.4343, 1.1373]]]])


### 取余与取整运算

In [2]:
import torch

a = torch.rand(2,2)
a = a * 10
print(a)
#向下取整
print(torch.floor(a))
# 向上取整
print(torch.ceil(a))
# 四舍五入
print(torch.round(a))
# 去除小数部分
print(torch.trunc(a))
# 取小数部分
print(torch.frac(a))
# 对2 取余
print(a % 2)


tensor([[5.0465, 9.7614],
        [5.0550, 0.7802]])
tensor([[5., 9.],
        [5., 0.]])
tensor([[ 6., 10.],
        [ 6.,  1.]])
tensor([[ 5., 10.],
        [ 5.,  1.]])
tensor([[5., 9.],
        [5., 0.]])
tensor([[0.0465, 0.7614],
        [0.0550, 0.7802]])
tensor([[1.0465, 1.7614],
        [1.0550, 0.7802]])


### 比较运算